# 生产环境配置（服务器配置）
# ⚠️ 部署前请修改以下配置为实际服务器配置：
#   1. 数据库连接信息（host、username、password）
#   2. Redis连接信息（host、password）
#   3. MongoDB连接信息（uri）
#   4. 文件上传路径和访问地址
#   5. CORS跨域配置（allowed-origins）

server:
  port: 20250
  address: 0.0.0.0  # 监听所有网络接口，允许外部访问

# CORS跨域配置（生产环境）
cors:
  # 允许的前端地址（根据实际域名修改）
  allowed-origins:
    # 本地开发地址
    - http://localhost:3000
    - http://localhost:3100
    - http://localhost:3101
    - http://localhost:5173
    - http://127.0.0.1:3000
    - http://127.0.0.1:3100
    - http://127.0.0.1:3101
    # 服务器地址
    - http://159.75.243.81
    - http://159.75.243.81:3000
    - https://159.75.243.81
    # 添加其他需要的前端地址
  # 允许的HTTP方法
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    - PATCH
  # 允许的请求头
  allowed-headers: '*'
  # 是否允许携带Cookie
  allow-credentials: true
  # 预检请求缓存时间（秒）
  max-age: 7200

# 数据源配置（生产环境）
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接URL（修改为实际服务器地址）
    url: jdbc:mysql://localhost:3306/xl_im?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    # 数据库用户名
    username: root
    # 数据库密码（⚠️ 请修改为实际密码）
    password: 200403281536Wgz
  
  # Redis配置（生产环境）
  data:
    redis:
      host: localhost
      port: 6379
      # Redis密码（如果设置了密码，请填写）
      password: 
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          min-idle: 0
          max-idle: 8

    # MongoDB配置（生产环境）
    mongodb:
      # MongoDB连接URI（修改为实际服务器地址）
      uri: mongodb://localhost:27017/xl_im
      database: xl_im

# 日志配置（使用logback-spring.xml配置）
logging:
  level:
    com.xl: info
    org.springframework.web: warn
  # 日志配置文件路径（使用logback-spring.xml）
  config: classpath:logback-spring.xml

# 文件上传配置（生产环境）
file:
  upload:
    # 文件存储路径（绝对路径）
    path: /www/wwwroot/uploads
    # 文件访问基础URL（根据实际域名修改）
    base-url: http://159.75.243.81/uploads
    # 最大文件大小（字节），默认10MB
    max-size: 10485760

