# 开发环境配置
# 开发环境可以直接写密码，因为不会部署到生产环境
server:
  port: 20250

# CORS跨域配置（开发环境）
cors:
  # 允许的前端地址
  allowed-origins:
    - http://localhost:3000
    - http://localhost:3100
    - http://localhost:3101
    - http://localhost:5173
    - http://127.0.0.1:3000
    - http://127.0.0.1:3100
    - http://127.0.0.1:3101
  # 允许的HTTP方法
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    - PATCH
  # 允许的请求头
  allowed-headers: '*'
  # 是否允许携带Cookie
  allow-credentials: true
  # 预检请求缓存时间（秒）
  max-age: 3600

# 日志配置
logging:
  level:
    com.xl: debug
    org.springframework.web: debug

