# 生产环境配置
server:
  port: 20250

# CORS跨域配置（生产环境 - 严格模式）
cors:
  # 只允许明确的生产域名（不使用通配符）
  allowed-origins:
    - https://www.yoursite.com
    - https://admin.yoursite.com
    # 根据实际生产域名修改
  # 允许的HTTP方法
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  # 允许的请求头（生产环境建议明确指定）
  allowed-headers:
    - Content-Type
    - Authorization
    - X-Requested-With
  # 是否允许携带Cookie
  allow-credentials: true
  # 预检请求缓存时间（秒）
  max-age: 7200

# 数据源配置（生产环境应该使用独立配置）
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://prod-mysql-host:3306/xl_im?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: ${DB_USERNAME:root}  # 使用环境变量
    password: ${DB_PASSWORD}       # 使用环境变量
  
  # Redis配置
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0

# 日志配置
logging:
  level:
    com.xl: info
    org.springframework.web: warn
  file:
    name: /var/log/xl-im/application.log
    max-size: 10MB
    max-history: 30

